# Generated by Django 5.2.10 on 2026-02-05 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cafes/'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='opening_hours',
            field=models.CharField(default='08:00 - 22:00', max_length=100),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='maps.cafe')),
            ],
        ),
    ]
