# Generated by Django 6.0.3 on 2026-04-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_branch_remove_cafe_slug_cafeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeimage',
            name='image',
            field=models.ImageField(upload_to='cafes/gallery/'),
        ),
    ]
