# Generated by Django 5.2.10 on 2026-04-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_cafeimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cafes/gallery/'),
        ),
    ]
