# Generated by Django 5.2.10 on 2026-02-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
