# Generated by Django 5.2.10 on 2026-04-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_booking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
    ]
