# Generated by Django 5.2.10 on 2026-04-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_remove_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='capacity',
            field=models.IntegerField(default=50),
        ),
    ]
