# Generated by Django 6.0.3 on 2026-04-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_event_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/main/', verbose_name='Ảnh chính'),
        ),
    ]
