# Generated by Django 6.0.3 on 2026-04-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_alter_eventimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/main/', verbose_name='Ảnh chính'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(default='', upload_to='events/', verbose_name='Ảnh sự kiện'),
            preserve_default=False,
        ),
    ]
