# Generated by Django 6.0.3 on 2026-04-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_event_image_alter_eventimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả ngắn'),
        ),
    ]
