# Generated by Django 6.0.3 on 2026-04-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_event_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cafe',
        ),
        migrations.AddField(
            model_name='product',
            name='cafes',
            field=models.ManyToManyField(blank=True, related_name='products', to='maps.cafe'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
