# Generated by Django 6.0.3 on 2026-04-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_remove_product_cafe_product_cafes_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='KATINAT - BẢN TUYÊN NGÔN DI SẢN VÀ NGHỆ THUẬT GIAO THOA ĐA TẦNG', max_length=255, verbose_name='Tiêu đề chính')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Ảnh 1 (Quán Katinat)')),
                ('text_1', models.TextField(blank=True, null=True, verbose_name='Đoạn văn 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Ảnh 2 (Pha trà)')),
                ('title_2', models.CharField(default='🍃 Tinh Tuyển Từ Nguồn Gốc - Lời hồi đáp từ đất mẹ linh thiêng', max_length=255, verbose_name='Tiêu đề đoạn 2')),
                ('text_2', models.TextField(blank=True, null=True, verbose_name='Đoạn văn 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Ảnh 3 (Ly cờ đỏ)')),
                ('title_3', models.CharField(default='🥛 Nghệ Thuật Phối Trộn Đa Tầng - Bản giao hưởng của những giác quan đương đại', max_length=255, verbose_name='Tiêu đề đoạn 3')),
                ('text_3', models.TextField(blank=True, null=True, verbose_name='Đoạn văn 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Ảnh 4 (Đồng hồ/Không gian)')),
                ('title_4', models.CharField(default='✨ Hơn Cả Một Vị Giác - Điểm chạm của cảm xúc và phong cách sống', max_length=255, verbose_name='Tiêu đề đoạn 4')),
                ('text_4', models.TextField(blank=True, null=True, verbose_name='Đoạn văn 4')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='anecdote',
            field=models.TextField(blank=True, null=True, verbose_name='4. Giai thoại'),
        ),
        migrations.AddField(
            model_name='product',
            name='brewing_method',
            field=models.TextField(blank=True, null=True, verbose_name='3. Tâm pháp pha chế'),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.TextField(blank=True, null=True, verbose_name='2. Nguồn gốc'),
        ),
        migrations.AddField(
            model_name='product',
            name='philosophy',
            field=models.TextField(blank=True, null=True, verbose_name='5. Cảm thức nhân sinh'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1. Mô tả ngắn'),
        ),
    ]
