# Generated by Django 6.0.3 on 2026-04-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_brandstory_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandstory',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Ảnh 5'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='text_5',
            field=models.TextField(blank=True, null=True, verbose_name='Đoạn văn 5'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='title_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề đoạn 5'),
        ),
    ]
