# Generated by Django 6.0.3 on 2026-04-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_brandstory_image_5_brandstory_text_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandstory',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Ảnh 10'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Ảnh 6'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Ảnh 7'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Ảnh 8'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='stories/', verbose_name='Ảnh 9'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='text_10',
            field=models.TextField(blank=True, null=True, verbose_name='Đoạn văn 10'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='text_6',
            field=models.TextField(blank=True, null=True, verbose_name='Đoạn văn 6'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='text_7',
            field=models.TextField(blank=True, null=True, verbose_name='Đoạn văn 7'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='text_8',
            field=models.TextField(blank=True, null=True, verbose_name='Đoạn văn 8'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='text_9',
            field=models.TextField(blank=True, null=True, verbose_name='Đoạn văn 9'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='title_10',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề đoạn 10'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='title_6',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề đoạn 6'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='title_7',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề đoạn 7'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='title_8',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề đoạn 8'),
        ),
        migrations.AddField(
            model_name='brandstory',
            name='title_9',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề đoạn 9'),
        ),
    ]
